version: '3.4'
services:
  mariadb:
    image: mysql:8.0 # mariadb:11.5.2
    ports:
      - "13306:3306"
    command:
      --init-file /data/application/DB.sql
    environment:
      MYSQL_ROOT_USER: javafxTest
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: vetcli
      MYSQL_USER: javafxTest
      MYSQL_PASSWORD: 7771
    volumes:
      - C:\Users\malin\IdeaProjects\practica\db/mariadb:/var/lib/mysql
      - C:\Users\malin\IdeaProjects\practica\db\DB.sql:/data/application/DB.sql

    # network_mode: "host"